version: '2'
services:
  aws_shadowsocks:
    image: 'bingoku/shadowsocks'
    ports:
      - "8388:8388"
    volumes:
      - ./config/shadowsokets.json:/etc/shadowsocks.json:rw
    command: -c /etc/shadowsocks.json
    environment: 
      - SERVER_ADDR=0.0.0.0
      - METHOD=aes-256-cfb
      - TIMEOUT=600
      - FAST_OPEN_ENABLE="true"